import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Poker NL2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto mt-8">
          <div className="buttons flex gap-2">
            <Link href="/preflop">
              <Button>Preflop</Button>
            </Link>
            <Link href="/flop">
              <Button>Flop</Button>
            </Link>
            <Link href="/turn">
              <Button>Turn</Button>
            </Link>
            <Link href="/river">
              <Button>River</Button>
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
